"""A script that moves all scatter plots and histograms generated by the search to centralized locations in the pwd."""
import glob
import os
import shutil
import sys

# Adds grandparent directory to sys.path. Necessary to make the import below work when running this file as a script
if __name__ == '__main__':
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.realpath(__file__)))))

import tgfsearch.parameters as params
import tgfsearch.tools as tl
from tgfsearch.search import is_valid_search


def is_valid_dir_path(path):
    if os.path.exists(path):
        if os.path.isdir(path):
            return True

        return False

    try:
        os.mkdir(path)
        os.rmdir(path)
    except Exception:
        return False

    return True


def main():
    if len(sys.argv) >= 4:
        first_date = str(sys.argv[1])
        second_date = str(sys.argv[2])
        unit = str(sys.argv[3]).upper()
    else:
        print('Error: please provide a first date, a second date, and a detector name.')
        exit()

    # Makes sure inputs are valid
    if not is_valid_search(first_date, second_date, unit, print_feedback=True):
        exit()

    if len(sys.argv) > 4:
        mode_info = sys.argv[4:]
    else:
        mode_info = []

    # Flag for using custom import/export directories
    results_loc = os.getcwd()
    export_loc = os.getcwd()
    if '-c' in mode_info:
        index = mode_info.index('-c')
        if index + 2 < len(mode_info):
            results_index = index + 1
            if mode_info[results_index] != 'none' and mode_info[results_index] != '/':
                if not is_valid_dir_path(mode_info[results_index]):
                    print('Error: invalid results path.')
                    exit()

                results_loc = mode_info[results_index]

            export_index = index + 2
            if mode_info[export_index] != 'none' and mode_info[export_index] != '/':
                if not is_valid_dir_path(mode_info[export_index]):
                    print('Error: invalid export path.')
                    exit()

                export_loc = mode_info[export_index]

        else:
            print("Error: please provide custom import and export directories, or 'none' in place of either.")
            exit()

    # Flag for only including short events above or equal to a certain rank
    max_rank = 0
    max_rank_order = 0
    rank_len = 0
    padding_len = 0
    if '-tr' in mode_info:
        index = mode_info.index('-tr')
        # Default argument (top-ranked plots only)
        if index + 1 >= len(mode_info) or not mode_info[index + 1].isnumeric() or int(mode_info[index + 1]) < 0:
            max_rank = 1
            max_rank_order = 1
        else:
            max_rank = int(mode_info[index + 1])
            max_rank_order = len(mode_info[index + 1])

        rank_len = len(str(params.MAX_PLOTS_PER_SCINT))
        padding_len = rank_len - max_rank_order

    # Flag for only including short events with greater than or equal to a certain score
    min_score = 0.
    if '-ms' in mode_info:
        index = mode_info.index('-ms')
        try:  # Checking that the argument can be converted into a float
            if index + 1 < len(mode_info) and float(mode_info[index + 1]) > 0:
                min_score = float(mode_info[index + 1])

        except ValueError:
            pass

    detector_path = f'{results_loc}/Results/{unit}'
    export_path = f'{export_loc}/collected_images'

    # For the traces
    trace_path = f'{export_path}/{unit}/traces'

    # For the scatter plots
    short_event_path = f'{export_path}/{unit}/scatter_plots'

    # For the histograms
    short_hist_path = f'{export_path}/{unit}/histograms/{params.SHORT_BIN_SIZE}_sec_bins'
    long_hist_path = f'{export_path}/{unit}/histograms/{params.LONG_BIN_SIZE}_sec_bins'

    requested_dates = tl.make_date_list(first_date, second_date)
    for date_str in requested_dates:
        path = f'{detector_path}/{date_str}'

        # Traces
        trace_list = glob.glob(f'{path}/traces/*xtr*.png')
        if len(trace_list) > 0:
            tl.make_path(trace_path)

        for trace in trace_list:
            t_filename = trace.split('/')[-1].split('\\')[-1]
            shutil.copyfile(trace, f'{trace_path}/{t_filename}')

        # Scatter plots:
        if max_rank > 0:
            top_plot_list = glob.glob(f'{path}/scatter_plots/'
                                      f'*_rank{"0" * padding_len}{"[0-9]" * max_rank_order}_score*.png')
            scatter_plot_list = []
            for plot in top_plot_list:
                rank_index = plot.find('rank') + 4
                rank = int(plot[rank_index: rank_index + rank_len])
                if rank <= max_rank:
                    scatter_plot_list.append(plot)

        else:
            scatter_plot_list = glob.glob(f'{path}/scatter_plots/*_rank*_score*.png')

        if min_score > 0:
            top_plot_list = []
            for plot in scatter_plot_list:
                score = float(plot.split('score')[-1].split('.')[0].replace('p', '.'))
                if score >= min_score:
                    top_plot_list.append(plot)

            scatter_plot_list = top_plot_list

        if len(scatter_plot_list) > 0:
            tl.make_path(short_event_path)

        for plot in scatter_plot_list:
            s_filename = plot.split('/')[-1].split('\\')[-1]
            shutil.copyfile(plot, f'{short_event_path}/{s_filename}')

        # Histograms
        short_hist_list = glob.glob(f'{path}/{date_str}_histogram_{params.SHORT_BIN_SIZE}_sec_bins_*_events.png')
        short_path_made = False
        for hist in short_hist_list:
            hist_filename = hist.split('/')[-1].split('\\')[-1]
            if int(hist_filename.split('_')[5]) > 0:
                if not short_path_made:
                    tl.make_path(short_hist_path)
                    short_path_made = True

                shutil.copyfile(hist, f'{short_hist_path}/{hist_filename}')

        long_hist_list = glob.glob(f'{path}/{date_str}_histogram_{params.LONG_BIN_SIZE}_sec_bins_*_events.png')
        long_path_made = False
        for hist in long_hist_list:
            hist_filename = hist.split('/')[-1].split('\\')[-1]
            if int(hist_filename.split('_')[5]) > 0:
                if not long_path_made:
                    tl.make_path(long_hist_path)
                    long_path_made = True

                shutil.copyfile(hist, f'{long_hist_path}/{hist_filename}')


if __name__ == '__main__':
    main()
