"""A script that moves all scatter plots and histograms generated by the search to centralized locations in the pwd."""
import argparse
import glob
import os
import shutil
import sys

# Adds grandparent directory to sys.path. Necessary to make the import below work when running this file as a script
if __name__ == '__main__':
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.realpath(__file__)))))

import tgfsearch.config.parameters as params
import tgfsearch.helpers.helper_funcs as helper_funcs
from tgfsearch.tools.tools import is_valid_detector


def main() -> None:
    parser = argparse.ArgumentParser(prog='tgfsearch-collect',
                                     description='A tgfsearch package utility that collects image files generated by '
                                                 'the search program in a centralized location.')

    # Primary arguments
    parser.add_argument('first_date', help='The first date in the range of dates to collect images for')
    parser.add_argument('second_date', help='The last date in the range of dates to collect images for')
    parser.add_argument('detector', help='The instrument that images will be collected for')

    # Flags
    parser.add_argument('--results-loc', default='',
                        help='The location of the results directory. Present working directory by default')
    parser.add_argument('--collection-loc', default='',
                        help='The location where the collected images directory will be created. Present working '
                             'directory by default')
    parser.add_argument('-tr', type=int, nargs='?', const=1, default=0,
                        help="Only include top-ranked short events. Only short events with a rank higher than or equal "
                             "to the provided rank (or rank 1 if it isn't provided) will be collected")
    parser.add_argument('-ms', type=float, default=0,
                        help='Only include short events with a score greater than or equal to the provided value')

    args = parser.parse_args()

    # Coercing/validating input and setting up the parameters
    try:
        first_date = helper_funcs.yymmdd_to_date(args.first_date)
        second_date = helper_funcs.yymmdd_to_date(args.second_date)
    except ValueError:
        print('Error: one or both dates is invalid. Both dates must be in YYMMDD format.')
        exit()

    if second_date > first_date:
        print('Error: second date must be after first date.')
        exit()

    if args.detector == '':
        print('Error: no detector specified.')
        exit()
    elif not is_valid_detector(args.detector):
        print('Error: not a valid detector.')
        exit()

    unit = args.detector.upper()

    if args.results_loc != '':
        if args.results_loc == '/':
            args.results_loc = ''
        else:
            if not helper_funcs.is_valid_dir_path(args.results_loc):
                print('Error: invalid results path.')
                exit()

    results_loc = args.results_loc

    if args.collection_loc != '':
        if args.collection_loc == '/':
            args.collection_loc = ''
        else:
            if not helper_funcs.is_valid_dir_path(args.collection_loc):
                print('Error: invalid collection path.')
                exit()

    collection_loc = args.collection_loc

    max_rank = args.tr

    min_score = args.ms

    detector_path = f'{results_loc}/Results/{unit}' if results_loc != '' else f'Results/{unit}'
    export_path = f'{collection_loc}/collected_images' if collection_loc != '' else 'collected_images'

    # For the traces
    trace_path = f'{export_path}/{unit}/traces'

    # For the scatter plots
    short_event_path = f'{export_path}/{unit}/scatter_plots'

    # For the histograms
    short_hist_path = f'{export_path}/{unit}/histograms/{params.SHORT_BIN_SIZE}_sec_bins'
    long_hist_path = f'{export_path}/{unit}/histograms/{params.LONG_BIN_SIZE}_sec_bins'

    requested_dates = helper_funcs.get_date_list(first_date, second_date)
    for date in requested_dates:
        path = f'{detector_path}/{helper_funcs.date_to_yymmdd(date)}'

        # Traces
        trace_list = glob.glob(f'{path}/traces/*xtr*.png')
        if len(trace_list) > 0:
            helper_funcs.make_path(trace_path)

        for trace in trace_list:
            t_filename = trace.split('/')[-1].split('\\')[-1]
            shutil.copyfile(trace, f'{trace_path}/{t_filename}')

        # Scatter plots:
        if max_rank > 0:
            max_rank_order = len(str(max_rank))
            rank_len = len(str(params.MAX_PLOTS_PER_SCINT))
            padding_len = rank_len - max_rank_order
            top_plot_list = glob.glob(f'{path}/scatter_plots/'
                                      f'*_rank{"0" * padding_len}{"[0-9]" * max_rank_order}_score*.png')
            scatter_plot_list = []
            for plot in top_plot_list:
                rank_index = plot.find('rank') + 4
                rank = int(plot[rank_index: rank_index + rank_len])
                if rank <= max_rank:
                    scatter_plot_list.append(plot)

        else:
            scatter_plot_list = glob.glob(f'{path}/scatter_plots/*_rank*_score*.png')

        if min_score > 0:
            top_plot_list = []
            for plot in scatter_plot_list:
                score = float(plot.split('score')[-1].split('.')[0].replace('p', '.'))
                if score >= min_score:
                    top_plot_list.append(plot)

            scatter_plot_list = top_plot_list

        if len(scatter_plot_list) > 0:
            helper_funcs.make_path(short_event_path)

        for plot in scatter_plot_list:
            s_filename = plot.split('/')[-1].split('\\')[-1]
            shutil.copyfile(plot, f'{short_event_path}/{s_filename}')

        # Histograms
        short_hist_list = glob.glob(f'{path}/{helper_funcs.date_to_yymmdd(date)}_histogram_{params.SHORT_BIN_SIZE}_sec_'
                                    f'bins_*_events.png')
        short_path_made = False
        for hist in short_hist_list:
            hist_filename = hist.split('/')[-1].split('\\')[-1]
            if int(hist_filename.split('_')[5]) > 0:
                if not short_path_made:
                    helper_funcs.make_path(short_hist_path)
                    short_path_made = True

                shutil.copyfile(hist, f'{short_hist_path}/{hist_filename}')

        long_hist_list = glob.glob(f'{path}/{helper_funcs.date_to_yymmdd(date)}_histogram_{params.LONG_BIN_SIZE}_sec_'
                                   f'bins_*_events.png')
        long_path_made = False
        for hist in long_hist_list:
            hist_filename = hist.split('/')[-1].split('\\')[-1]
            if int(hist_filename.split('_')[5]) > 0:
                if not long_path_made:
                    helper_funcs.make_path(long_hist_path)
                    long_path_made = True

                shutil.copyfile(hist, f'{long_hist_path}/{hist_filename}')


if __name__ == '__main__':
    main()
